apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeusers
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:
        - name: kubecontainer
          image: bidabehere/nodeapp:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: "mongodb+srv://bidabehere:bidabehere@cluster0.a5dcy.mongodb.net/Coder51420"
          imagePullPolicy: Always
